// ============================================================
// DOC TEMPLATES — 22 placeholder-based templates
// User data fills {{fields}} automatically
// ============================================================

export type DocCategory = 'business' | 'resume' | 'school' | 'personal';

export interface DocSection {
  type: 'heading' | 'subheading' | 'paragraph' | 'table' | 'list' | 'spacer' | 'divider' | 'logo-placeholder';
  text?: string;
  rows?: string[][];
  items?: string[];
  level?: 1 | 2 | 3;
  bold?: boolean;
  italic?: boolean;
  alignment?: 'left' | 'center' | 'right';
  color?: string;
  size?: number;
}

export interface DocTemplate {
  id: string;
  name: string;
  category: DocCategory;
  description: string;
  keywords: string[];
  sections: DocSection[];
  fileName: string;
}

// ============================================================
// 1. PROFESSIONAL INVOICE
// ============================================================
const invoice: DocTemplate = {
  id: 'invoice',
  name: 'Professional Invoice',
  category: 'business',
  description: 'Standard business invoice with company details, line items, and totals',
  keywords: ['invoice', 'bill', 'billing', 'invoice doc', 'invoice document'],
  fileName: 'Invoice.docx',
  sections: [
    { type: 'logo-placeholder', alignment: 'left' },
    { type: 'spacer' },
    { type: 'heading', text: 'INVOICE', alignment: 'right', size: 32, color: '#6D28D9' },
    { type: 'spacer' },
    { type: 'heading', text: '{{companyName}}', level: 2, color: '#111827' },
    { type: 'paragraph', text: '{{companyAddress}}' },
    { type: 'paragraph', text: 'Phone: {{companyPhone}}' },
    { type: 'paragraph', text: 'Email: {{companyEmail}}' },
    { type: 'spacer' },
    { type: 'divider' },
    { type: 'spacer' },
    { type: 'heading', text: 'Bill To:', level: 3, bold: true },
    { type: 'paragraph', text: '{{clientName}}' },
    { type: 'paragraph', text: '{{clientAddress}}' },
    { type: 'paragraph', text: 'Email: {{clientEmail}}' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'Invoice Number: {{invoiceNumber}}', bold: true },
    { type: 'paragraph', text: 'Invoice Date: {{date}}' },
    { type: 'paragraph', text: 'Due Date: {{dueDate}}' },
    { type: 'paragraph', text: 'Payment Terms: {{paymentTerms}}' },
    { type: 'spacer' },
    { type: 'spacer' },
    {
      type: 'table',
      rows: [
        ['#', 'Description', 'Qty', 'Unit Price', 'Amount'],
        ['1', '{{item1Desc}}', '{{item1Qty}}', '{{item1Price}}', '{{item1Amount}}'],
        ['2', '{{item2Desc}}', '{{item2Qty}}', '{{item2Price}}', '{{item2Amount}}'],
        ['3', '{{item3Desc}}', '{{item3Qty}}', '{{item3Price}}', '{{item3Amount}}'],
        ['4', '{{item4Desc}}', '{{item4Qty}}', '{{item4Price}}', '{{item4Amount}}'],
        ['5', '{{item5Desc}}', '{{item5Qty}}', '{{item5Price}}', '{{item5Amount}}'],
        ['', '', '', 'Subtotal:', '{{subtotal}}'],
        ['', '', '', 'Tax:', '{{tax}}'],
        ['', '', '', 'TOTAL DUE:', '{{total}}'],
      ],
    },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'divider' },
    { type: 'heading', text: 'Payment Details', level: 3, bold: true },
    { type: 'paragraph', text: '{{paymentDetails}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'Notes', level: 3, bold: true },
    { type: 'paragraph', text: '{{notes}}' },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'Authorized Signature: _______________________', italic: true },
    { type: 'paragraph', text: 'Date: _______________________', italic: true },
  ],
};

// ============================================================
// 2. BUSINESS PROPOSAL
// ============================================================
const businessProposal: DocTemplate = {
  id: 'business-proposal',
  name: 'Business Proposal',
  category: 'business',
  description: 'Professional project proposal for clients and stakeholders',
  keywords: ['business proposal', 'proposal', 'project proposal', 'client proposal'],
  fileName: 'Business_Proposal.docx',
  sections: [
    { type: 'logo-placeholder', alignment: 'center' },
    { type: 'spacer' },
    { type: 'heading', text: 'BUSINESS PROPOSAL', alignment: 'center', size: 28, color: '#6D28D9' },
    { type: 'paragraph', text: '{{projectTitle}}', alignment: 'center', italic: true, size: 14 },
    { type: 'spacer' },
    { type: 'divider' },
    { type: 'spacer' },
    { type: 'heading', text: 'Prepared For', level: 3, bold: true },
    { type: 'paragraph', text: '{{clientName}}' },
    { type: 'paragraph', text: '{{clientAddress}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'Prepared By', level: 3, bold: true },
    { type: 'paragraph', text: '{{companyName}}' },
    { type: 'paragraph', text: '{{companyAddress}}' },
    { type: 'paragraph', text: 'Contact: {{contactPerson}}' },
    { type: 'paragraph', text: 'Email: {{companyEmail}} | Phone: {{companyPhone}}' },
    { type: 'spacer' },
    { type: 'heading', text: '1. Executive Summary', level: 2, color: '#6D28D9' },
    { type: 'paragraph', text: '{{executiveSummary}}' },
    { type: 'spacer' },
    { type: 'heading', text: '2. Project Objectives', level: 2, color: '#6D28D9' },
    { type: 'paragraph', text: '{{objectives}}' },
    { type: 'spacer' },
    { type: 'heading', text: '3. Scope of Work', level: 2, color: '#6D28D9' },
    { type: 'paragraph', text: '{{scopeOfWork}}' },
    { type: 'spacer' },
    { type: 'heading', text: '4. Project Timeline', level: 2, color: '#6D28D9' },
    { type: 'paragraph', text: '{{timeline}}' },
    { type: 'spacer' },
    { type: 'heading', text: '5. Investment', level: 2, color: '#6D28D9' },
    { type: 'paragraph', text: '{{investment}}' },
    { type: 'spacer' },
    { type: 'heading', text: '6. Why Choose Us', level: 2, color: '#6D28D9' },
    { type: 'paragraph', text: '{{whyChooseUs}}' },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'We look forward to partnering with you.', italic: true },
    { type: 'paragraph', text: '{{contactPerson}}', bold: true },
    { type: 'paragraph', text: '{{contactTitle}}, {{companyName}}' },
  ],
};

// ============================================================
// 3. MEETING MINUTES
// ============================================================
const meetingMinutes: DocTemplate = {
  id: 'meeting-minutes',
  name: 'Meeting Minutes',
  category: 'business',
  description: 'Professional meeting notes with attendees, agenda, and action items',
  keywords: ['meeting minutes', 'meeting notes', 'minutes of meeting', 'mom'],
  fileName: 'Meeting_Minutes.docx',
  sections: [
    { type: 'logo-placeholder', alignment: 'left' },
    { type: 'spacer' },
    { type: 'heading', text: 'MEETING MINUTES', alignment: 'center', size: 24, color: '#6D28D9' },
    { type: 'spacer' },
    { type: 'divider' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'Meeting Title: {{meetingTitle}}', bold: true, size: 14 },
    { type: 'paragraph', text: 'Date: {{date}}' },
    { type: 'paragraph', text: 'Time: {{time}}' },
    { type: 'paragraph', text: 'Location: {{location}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'Attendees', level: 3, bold: true },
    { type: 'paragraph', text: '{{attendees}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'Agenda', level: 3, bold: true },
    { type: 'paragraph', text: '{{agenda}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'Discussion Points', level: 3, bold: true },
    { type: 'paragraph', text: '{{discussion}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'Action Items', level: 3, bold: true },
    { type: 'paragraph', text: '{{actionItems}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'Decisions Made', level: 3, bold: true },
    { type: 'paragraph', text: '{{decisions}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'Next Meeting', level: 3, bold: true },
    { type: 'paragraph', text: 'Date: {{nextMeetingDate}}' },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'Minutes prepared by: {{preparedBy}}', italic: true },
    { type: 'paragraph', text: 'Approved by: {{approvedBy}}', italic: true },
  ],
};

// ============================================================
// 4. ATS RESUME
// ============================================================
const atsResume: DocTemplate = {
  id: 'ats-resume',
  name: 'ATS Resume',
  category: 'resume',
  description: 'ATS-friendly resume optimized for applicant tracking systems',
  keywords: ['ats resume', 'resume', 'cv', 'ats cv', 'ats friendly resume'],
  fileName: 'ATS_Resume.docx',
  sections: [
    { type: 'heading', text: '{{fullName}}', alignment: 'center', size: 22, color: '#111827' },
    { type: 'paragraph', text: '{{jobTitle}}', alignment: 'center', italic: true, size: 13 },
    { type: 'paragraph', text: '{{email}} | {{phone}} | {{location}}', alignment: 'center', size: 10 },
    { type: 'paragraph', text: '{{linkedin}}', alignment: 'center', size: 10 },
    { type: 'spacer' },
    { type: 'divider' },
    { type: 'spacer' },
    { type: 'heading', text: 'PROFESSIONAL SUMMARY', level: 2, color: '#111827' },
    { type: 'paragraph', text: '{{summary}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'CORE COMPETENCIES', level: 2, color: '#111827' },
    { type: 'paragraph', text: '{{skills}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'PROFESSIONAL EXPERIENCE', level: 2, color: '#111827' },
    { type: 'paragraph', text: '{{experience}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'EDUCATION', level: 2, color: '#111827' },
    { type: 'paragraph', text: '{{education}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'CERTIFICATIONS', level: 2, color: '#111827' },
    { type: 'paragraph', text: '{{certifications}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'PROJECTS', level: 2, color: '#111827' },
    { type: 'paragraph', text: '{{projects}}' },
  ],
};

// ============================================================
// 5. MODERN RESUME
// ============================================================
const modernResume: DocTemplate = {
  id: 'modern-resume',
  name: 'Modern Resume',
  category: 'resume',
  description: 'Creative and modern resume design for design and tech roles',
  keywords: ['modern resume', 'creative resume', 'designer resume', 'modern cv'],
  fileName: 'Modern_Resume.docx',
  sections: [
    { type: 'heading', text: '{{fullName}}', alignment: 'center', size: 28, color: '#6D28D9' },
    { type: 'paragraph', text: '{{jobTitle}}', alignment: 'center', italic: true, size: 15, color: '#6D28D9' },
    { type: 'spacer' },
    { type: 'paragraph', text: '{{email}}  •  {{phone}}  •  {{location}}', alignment: 'center', size: 10 },
    { type: 'paragraph', text: '{{linkedin}}', alignment: 'center', size: 10 },
    { type: 'spacer' },
    { type: 'divider' },
    { type: 'spacer' },
    { type: 'heading', text: 'ABOUT ME', level: 2, color: '#6D28D9' },
    { type: 'paragraph', text: '{{about}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'EXPERIENCE', level: 2, color: '#6D28D9' },
    { type: 'paragraph', text: '{{experience}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'SKILLS', level: 2, color: '#6D28D9' },
    { type: 'paragraph', text: '{{skills}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'EDUCATION', level: 2, color: '#6D28D9' },
    { type: 'paragraph', text: '{{education}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'AWARDS & RECOGNITION', level: 2, color: '#6D28D9' },
    { type: 'paragraph', text: '{{awards}}' },
  ],
};

// ============================================================
// 6. EUROPASS CV
// ============================================================
const europassCV: DocTemplate = {
  id: 'europass-cv',
  name: 'Europass CV',
  category: 'resume',
  description: 'Standard Europass CV format for European applications',
  keywords: ['europass', 'europass cv', 'european cv', 'eu cv'],
  fileName: 'Europass_CV.docx',
  sections: [
    { type: 'heading', text: 'Europass', alignment: 'left', size: 24, color: '#003399' },
    { type: 'paragraph', text: 'Curriculum Vitae', italic: true, size: 14 },
    { type: 'spacer' },
    { type: 'divider' },
    { type: 'spacer' },
    { type: 'heading', text: 'PERSONAL INFORMATION', level: 2, color: '#003399' },
    { type: 'paragraph', text: 'Name:  {{fullName}}', bold: true },
    { type: 'paragraph', text: 'Address:  {{address}}' },
    { type: 'paragraph', text: 'Phone:  {{phone}}' },
    { type: 'paragraph', text: 'Email:  {{email}}' },
    { type: 'paragraph', text: 'Nationality:  {{nationality}}' },
    { type: 'paragraph', text: 'Date of Birth:  {{dateOfBirth}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'WORK EXPERIENCE', level: 2, color: '#003399' },
    { type: 'paragraph', text: '{{workExperience}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'EDUCATION AND TRAINING', level: 2, color: '#003399' },
    { type: 'paragraph', text: '{{education}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'LANGUAGE SKILLS', level: 2, color: '#003399' },
    { type: 'paragraph', text: '{{languageSkills}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'DIGITAL SKILLS', level: 2, color: '#003399' },
    { type: 'paragraph', text: '{{digitalSkills}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'ADDITIONAL INFORMATION', level: 2, color: '#003399' },
    { type: 'paragraph', text: '{{additionalInfo}}' },
  ],
};

// ============================================================
// 7. COVER LETTER
// ============================================================
const coverLetter: DocTemplate = {
  id: 'cover-letter',
  name: 'Cover Letter',
  category: 'resume',
  description: 'Professional cover letter for job applications',
  keywords: ['cover letter', 'application letter', 'job letter'],
  fileName: 'Cover_Letter.docx',
  sections: [
    { type: 'paragraph', text: '{{fullName}}', bold: true, size: 14 },
    { type: 'paragraph', text: '{{address}}' },
    { type: 'paragraph', text: '{{email}} | {{phone}}' },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'paragraph', text: '{{date}}' },
    { type: 'spacer' },
    { type: 'paragraph', text: '{{recipientName}}' },
    { type: 'paragraph', text: '{{recipientTitle}}' },
    { type: 'paragraph', text: '{{company}}' },
    { type: 'paragraph', text: '{{companyAddress}}' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'Dear {{recipientName}},' },
    { type: 'spacer' },
    { type: 'paragraph', text: '{{bodyParagraphs}}' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'Sincerely,' },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'paragraph', text: '{{fullName}}', bold: true },
  ],
};

// ============================================================
// 8. PURCHASE ORDER
// ============================================================
const purchaseOrder: DocTemplate = {
  id: 'purchase-order',
  name: 'Purchase Order',
  category: 'business',
  description: 'Professional purchase order for suppliers and vendors',
  keywords: ['purchase order', 'po', 'supplier order', 'vendor order'],
  fileName: 'Purchase_Order.docx',
  sections: [
    { type: 'logo-placeholder', alignment: 'left' },
    { type: 'spacer' },
    { type: 'heading', text: 'PURCHASE ORDER', alignment: 'center', size: 24, color: '#6D28D9' },
    { type: 'spacer' },
    { type: 'divider' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'PO Number: {{poNumber}}', bold: true },
    { type: 'paragraph', text: 'Date: {{date}}' },
    { type: 'paragraph', text: 'Expected Delivery: {{expectedDelivery}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'Buyer Information', level: 3, bold: true, color: '#6D28D9' },
    { type: 'paragraph', text: '{{buyerName}}' },
    { type: 'paragraph', text: '{{buyerAddress}}' },
    { type: 'paragraph', text: 'Contact: {{buyerContact}}' },
    { type: 'paragraph', text: 'Email: {{buyerEmail}} | Phone: {{buyerPhone}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'Supplier Information', level: 3, bold: true, color: '#6D28D9' },
    { type: 'paragraph', text: '{{supplierName}}' },
    { type: 'paragraph', text: '{{supplierAddress}}' },
    { type: 'paragraph', text: 'Contact: {{supplierContact}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'Order Details', level: 3, bold: true, color: '#6D28D9' },
    {
      type: 'table',
      rows: [
        ['Item #', 'Description', 'Qty', 'Unit Price', 'Total'],
        ['001', '{{item1Desc}}', '{{item1Qty}}', '{{item1Price}}', '{{item1Total}}'],
        ['002', '{{item2Desc}}', '{{item2Qty}}', '{{item2Price}}', '{{item2Total}}'],
        ['003', '{{item3Desc}}', '{{item3Qty}}', '{{item3Price}}', '{{item3Total}}'],
        ['004', '{{item4Desc}}', '{{item4Qty}}', '{{item4Price}}', '{{item4Total}}'],
        ['005', '{{item5Desc}}', '{{item5Qty}}', '{{item5Price}}', '{{item5Total}}'],
        ['', '', '', 'Subtotal:', '{{subtotal}}'],
        ['', '', '', 'Tax:', '{{tax}}'],
        ['', '', '', 'Shipping:', '{{shipping}}'],
        ['', '', '', 'TOTAL:', '{{total}}'],
      ],
    },
    { type: 'spacer' },
    { type: 'heading', text: 'Shipping Address', level: 3, bold: true, color: '#6D28D9' },
    { type: 'paragraph', text: '{{shippingAddress}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'Terms & Conditions', level: 3, bold: true, color: '#6D28D9' },
    { type: 'paragraph', text: '{{terms}}' },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'Authorized By: _______________________', italic: true },
    { type: 'paragraph', text: '{{buyerContact}}', italic: true },
    { type: 'paragraph', text: 'Date: _______________________', italic: true },
  ],
};

// ============================================================
// 9. QUOTATION
// ============================================================
const quotation: DocTemplate = {
  id: 'quotation',
  name: 'Quotation',
  category: 'business',
  description: 'Professional price quotation for potential clients',
  keywords: ['quotation', 'quote', 'price quote', 'estimate'],
  fileName: 'Quotation.docx',
  sections: [
    { type: 'logo-placeholder', alignment: 'left' },
    { type: 'spacer' },
    { type: 'heading', text: 'QUOTATION', alignment: 'center', size: 28, color: '#6D28D9' },
    { type: 'spacer' },
    { type: 'divider' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'Quote Number: {{quoteNumber}}', bold: true },
    { type: 'paragraph', text: 'Date: {{date}}' },
    { type: 'paragraph', text: 'Valid Until: {{validUntil}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'From', level: 3, bold: true, color: '#6D28D9' },
    { type: 'paragraph', text: '{{companyName}}' },
    { type: 'paragraph', text: '{{companyAddress}}' },
    { type: 'paragraph', text: 'Email: {{companyEmail}} | Phone: {{companyPhone}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'To', level: 3, bold: true, color: '#6D28D9' },
    { type: 'paragraph', text: '{{clientName}}' },
    { type: 'paragraph', text: '{{clientAddress}}' },
    { type: 'paragraph', text: 'Attention: {{clientContact}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'Quotation Details', level: 3, bold: true, color: '#6D28D9' },
    {
      type: 'table',
      rows: [
        ['#', 'Item / Service', 'Qty', 'Rate', 'Amount'],
        ['1', '{{item1Desc}}', '{{item1Qty}}', '{{item1Rate}}', '{{item1Amount}}'],
        ['2', '{{item2Desc}}', '{{item2Qty}}', '{{item2Rate}}', '{{item2Amount}}'],
        ['3', '{{item3Desc}}', '{{item3Qty}}', '{{item3Rate}}', '{{item3Amount}}'],
        ['4', '{{item4Desc}}', '{{item4Qty}}', '{{item4Rate}}', '{{item4Amount}}'],
        ['5', '{{item5Desc}}', '{{item5Qty}}', '{{item5Rate}}', '{{item5Amount}}'],
        ['', '', '', 'Subtotal:', '{{subtotal}}'],
        ['', '', '', 'Tax:', '{{tax}}'],
        ['', '', '', 'Discount:', '{{discount}}'],
        ['', '', '', 'TOTAL:', '{{total}}'],
      ],
    },
    { type: 'spacer' },
    { type: 'heading', text: 'Terms & Conditions', level: 3, bold: true, color: '#6D28D9' },
    { type: 'paragraph', text: '{{terms}}' },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'We look forward to working with you.', italic: true },
    { type: 'spacer' },
    { type: 'paragraph', text: 'Authorized Signature: _______________________', italic: true },
    { type: 'paragraph', text: '{{companyName}}', italic: true },
  ],
};

// ============================================================
// 10. COMPANY LETTERHEAD
// ============================================================
const companyLetterhead: DocTemplate = {
  id: 'letterhead',
  name: 'Company Letterhead',
  category: 'business',
  description: 'Professional company letterhead for official correspondence',
  keywords: ['letterhead', 'company letterhead', 'official letter', 'business letter'],
  fileName: 'Company_Letterhead.docx',
  sections: [
    { type: 'logo-placeholder', alignment: 'center' },
    { type: 'spacer' },
    { type: 'heading', text: '{{companyName}}', alignment: 'center', size: 22, color: '#6D28D9' },
    { type: 'paragraph', text: '{{companyTagline}}', alignment: 'center', italic: true, size: 10 },
    { type: 'paragraph', text: '{{companyAddress}}', alignment: 'center', size: 9 },
    { type: 'paragraph', text: 'Phone: {{companyPhone}}  •  Email: {{companyEmail}}  •  {{companyWebsite}}', alignment: 'center', size: 9 },
    { type: 'spacer' },
    { type: 'divider' },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'paragraph', text: '{{date}}' },
    { type: 'spacer' },
    { type: 'paragraph', text: '{{recipientName}}' },
    { type: 'paragraph', text: '{{recipientTitle}}' },
    { type: 'paragraph', text: '{{recipientCompany}}' },
    { type: 'paragraph', text: '{{recipientAddress}}' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'Dear {{recipientName}},' },
    { type: 'spacer' },
    { type: 'heading', text: 'Re: {{subject}}', level: 3, bold: true },
    { type: 'spacer' },
    { type: 'paragraph', text: '{{body}}' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'Sincerely,' },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'paragraph', text: '{{senderName}}', bold: true },
    { type: 'paragraph', text: '{{senderTitle}}' },
    { type: 'paragraph', text: '{{companyName}}' },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'divider' },
    { type: 'paragraph', text: '{{companyName}}  •  {{companyWebsite}}  •  {{companyPhone}}', alignment: 'center', italic: true, size: 8 },
  ],
};

// ============================================================
// 11. CONTRACT AGREEMENT
// ============================================================
const contractAgreement: DocTemplate = {
  id: 'contract',
  name: 'Contract Agreement',
  category: 'business',
  description: 'Standard service contract agreement for clients',
  keywords: ['contract', 'agreement', 'service contract', 'legal contract'],
  fileName: 'Contract_Agreement.docx',
  sections: [
    { type: 'heading', text: 'SERVICE AGREEMENT CONTRACT', alignment: 'center', size: 20, color: '#6D28D9' },
    { type: 'spacer' },
    { type: 'divider' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'This Service Agreement ("Agreement") is entered into as of {{effectiveDate}} ("Effective Date"), by and between:', italic: true },
    { type: 'spacer' },
    { type: 'paragraph', text: 'SERVICE PROVIDER:', bold: true },
    { type: 'paragraph', text: '{{providerName}}, with its principal office at {{providerAddress}} ("Provider").' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'CLIENT:', bold: true },
    { type: 'paragraph', text: '{{clientName}}, with its principal office at {{clientAddress}} ("Client").' },
    { type: 'spacer' },
    { type: 'heading', text: '1. SCOPE OF SERVICES', level: 3, bold: true, color: '#6D28D9' },
    { type: 'paragraph', text: '{{scopeOfServices}}' },
    { type: 'spacer' },
    { type: 'heading', text: '2. TERM', level: 3, bold: true, color: '#6D28D9' },
    { type: 'paragraph', text: '{{term}}' },
    { type: 'spacer' },
    { type: 'heading', text: '3. COMPENSATION', level: 3, bold: true, color: '#6D28D9' },
    { type: 'paragraph', text: '{{compensation}}' },
    { type: 'spacer' },
    { type: 'heading', text: '4. CONFIDENTIALITY', level: 3, bold: true, color: '#6D28D9' },
    { type: 'paragraph', text: '{{confidentiality}}' },
    { type: 'spacer' },
    { type: 'heading', text: '5. INTELLECTUAL PROPERTY', level: 3, bold: true, color: '#6D28D9' },
    { type: 'paragraph', text: '{{intellectualProperty}}' },
    { type: 'spacer' },
    { type: 'heading', text: '6. TERMINATION', level: 3, bold: true, color: '#6D28D9' },
    { type: 'paragraph', text: '{{termination}}' },
    { type: 'spacer' },
    { type: 'heading', text: '7. GOVERNING LAW', level: 3, bold: true, color: '#6D28D9' },
    { type: 'paragraph', text: '{{governingLaw}}' },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'heading', text: 'SIGNATURES', level: 3, bold: true, color: '#6D28D9' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'FOR {{providerName}}:' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'Signature: _____________________________' },
    { type: 'paragraph', text: 'Name: {{providerSigner}}' },
    { type: 'paragraph', text: 'Title: {{providerTitle}}' },
    { type: 'paragraph', text: 'Date: _________________' },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'FOR {{clientName}}:' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'Signature: _____________________________' },
    { type: 'paragraph', text: 'Name: {{clientSigner}}' },
    { type: 'paragraph', text: 'Title: {{clientTitle}}' },
    { type: 'paragraph', text: 'Date: _________________' },
  ],
};

    
// ============================================================
// 12. STUDENT ID CARD
// ============================================================
const studentIdCard: DocTemplate = {
  id: 'student-id',
  name: 'Student ID Card',
  category: 'school',
  description: 'Student identity card with photo placeholder',
  keywords: ['student id', 'id card', 'student card', 'identity card'],
  fileName: 'Student_ID_Card.docx',
  sections: [
    { type: 'heading', text: 'STUDENT IDENTITY CARD', alignment: 'center', size: 16, color: '#6D28D9' },
    { type: 'spacer' },
    { type: 'divider' },
    { type: 'spacer' },
    { type: 'logo-placeholder', alignment: 'center' },
    { type: 'spacer' },
    { type: 'heading', text: '{{schoolName}}', alignment: 'center', size: 18, color: '#111827' },
    { type: 'paragraph', text: '{{schoolAddress}}', alignment: 'center' },
    { type: 'paragraph', text: 'Phone: {{schoolPhone}}  |  Email: {{schoolEmail}}', alignment: 'center' },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'paragraph', text: '[ STUDENT PHOTO HERE ]', alignment: 'center', bold: true },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'heading', text: 'STUDENT INFORMATION', level: 3, bold: true, color: '#6D28D9' },
    {
      type: 'table',
      rows: [
        ['Student Name:', '{{studentName}}'],
        ['Father\'s Name:', '{{fatherName}}'],
        ['Date of Birth:', '{{dateOfBirth}}'],
        ['Class:', '{{className}}'],
        ['Roll Number:', '{{rollNumber}}'],
        ['Session:', '{{session}}'],
        ['Blood Group:', '{{bloodGroup}}'],
        ['Address:', '{{address}}'],
        ['Emergency Contact:', '{{emergencyContact}}'],
      ],
    },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'paragraph', text: '_____________________              _____________________', alignment: 'center' },
    { type: 'paragraph', text: 'Principal Signature                        Valid Until: {{validUntil}}', alignment: 'center', italic: true, size: 9 },
  ],
};

// ============================================================
// 13. REPORT CARD
// ============================================================
const reportCard: DocTemplate = {
  id: 'report-card',
  name: 'Report Card',
  category: 'school',
  description: 'Student report card with grades and teacher comments',
  keywords: ['report card', 'marksheet', 'grade sheet', 'progress report'],
  fileName: 'Report_Card.docx',
  sections: [
    { type: 'logo-placeholder', alignment: 'center' },
    { type: 'spacer' },
    { type: 'heading', text: '{{schoolName}}', alignment: 'center', size: 20, color: '#6D28D9' },
    { type: 'paragraph', text: '{{schoolAddress}}', alignment: 'center', size: 10 },
    { type: 'paragraph', text: 'Phone: {{schoolPhone}}  |  Email: {{schoolEmail}}', alignment: 'center', size: 10 },
    { type: 'spacer' },
    { type: 'heading', text: 'STUDENT PROGRESS REPORT', alignment: 'center', size: 14, bold: true, color: '#111827' },
    { type: 'paragraph', text: 'Academic Year {{academicYear}}', alignment: 'center', italic: true, size: 11 },
    { type: 'spacer' },
    { type: 'divider' },
    { type: 'spacer' },
    { type: 'heading', text: 'Student Information', level: 3, bold: true, color: '#6D28D9' },
    {
      type: 'table',
      rows: [
        ['Student Name:', '{{studentName}}'],
        ['Roll Number:', '{{rollNumber}}'],
        ['Class:', '{{className}}'],
        ['Section:', '{{section}}'],
        ['Date of Birth:', '{{dateOfBirth}}'],
        ['Father\'s Name:', '{{fatherName}}'],
      ],
    },
    { type: 'spacer' },
    { type: 'heading', text: 'Academic Performance', level: 3, bold: true, color: '#6D28D9' },
    {
      type: 'table',
      rows: [
        ['Subject', 'Marks', 'Grade'],
        ['{{subject1}}', '{{marks1}}', '{{grade1}}'],
        ['{{subject2}}', '{{marks2}}', '{{grade2}}'],
        ['{{subject3}}', '{{marks3}}', '{{grade3}}'],
        ['{{subject4}}', '{{marks4}}', '{{grade4}}'],
        ['{{subject5}}', '{{marks5}}', '{{grade5}}'],
        ['{{subject6}}', '{{marks6}}', '{{grade6}}'],
      ],
    },
    { type: 'spacer' },
    { type: 'heading', text: 'Overall Performance', level: 3, bold: true, color: '#6D28D9' },
    {
      type: 'table',
      rows: [
        ['Total Marks Obtained:', '{{totalMarks}}'],
        ['Percentage:', '{{percentage}}'],
        ['Overall Grade:', '{{overallGrade}}'],
        ['Class Rank:', '{{classRank}}'],
        ['Attendance:', '{{attendance}}'],
      ],
    },
    { type: 'spacer' },
    { type: 'heading', text: 'Co-Curricular Activities', level: 3, bold: true, color: '#6D28D9' },
    { type: 'paragraph', text: '{{activities}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'Teacher\'s Comments', level: 3, bold: true, color: '#6D28D9' },
    { type: 'paragraph', text: '{{comments}}' },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'heading', text: 'Grading Scale', level: 3, bold: true, color: '#6D28D9' },
    { type: 'paragraph', text: 'A+ = 90-100%  |  A = 80-89%  |  B+ = 75-79%  |  B = 70-74%  |  C = 60-69%  |  D = 50-59%  |  F = Below 50%', size: 10 },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'paragraph', text: '_____________________              _____________________', alignment: 'center' },
    { type: 'paragraph', text: 'Class Teacher                              Principal', alignment: 'center', italic: true, size: 10 },
    { type: 'spacer' },
    { type: 'paragraph', text: 'Date of Issue: {{date}}', alignment: 'center', italic: true, size: 9 },
  ],
};

// ============================================================
// 14. CERTIFICATE OF ACHIEVEMENT
// ============================================================
const certificateAchievement: DocTemplate = {
  id: 'certificate',
  name: 'Certificate of Achievement',
  category: 'school',
  description: 'Elegant certificate for awards and recognition',
  keywords: ['certificate', 'achievement', 'award', 'certificate of achievement'],
  fileName: 'Certificate_of_Achievement.docx',
  sections: [
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'logo-placeholder', alignment: 'center' },
    { type: 'spacer' },
    { type: 'heading', text: 'CERTIFICATE OF ACHIEVEMENT', alignment: 'center', size: 32, color: '#6D28D9' },
    { type: 'spacer' },
    { type: 'divider' },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'This Certificate is Proudly Presented To', alignment: 'center', italic: true, size: 14 },
    { type: 'spacer' },
    { type: 'heading', text: '{{recipientName}}', alignment: 'center', size: 36, color: '#111827' },
    { type: 'spacer' },
    { type: 'divider' },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'For outstanding performance and dedication in', alignment: 'center', size: 13 },
    { type: 'spacer' },
    { type: 'paragraph', text: '{{eventName}}', alignment: 'center', bold: true, size: 18, color: '#6D28D9' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'held on {{eventDate}} at {{eventLocation}}', alignment: 'center', italic: true, size: 11 },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'paragraph', text: '{{description}}' },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'paragraph', text: '_____________________              _____________________', alignment: 'center' },
    { type: 'paragraph', text: '{{signer1Name}}                        {{signer2Name}}', alignment: 'center', italic: true, size: 10 },
    { type: 'paragraph', text: '{{signer1Title}}                                {{signer2Title}}', alignment: 'center', italic: true, size: 9 },
    { type: 'spacer' },
    { type: 'paragraph', text: 'Date: {{date}}', alignment: 'center', italic: true, size: 10 },
  ],
};

// ============================================================
// 15. ADMISSION FORM
// ============================================================
const admissionForm: DocTemplate = {
  id: 'admission-form',
  name: 'Admission Form',
  category: 'school',
  description: 'Complete student admission form for schools',
  keywords: ['admission form', 'student admission', 'enrollment form', 'school admission'],
  fileName: 'Admission_Form.docx',
  sections: [
    { type: 'logo-placeholder', alignment: 'center' },
    { type: 'spacer' },
    { type: 'heading', text: '{{schoolName}}', alignment: 'center', size: 20, color: '#6D28D9' },
    { type: 'paragraph', text: '{{schoolAddress}}', alignment: 'center', size: 10 },
    { type: 'paragraph', text: 'Phone: {{schoolPhone}}  |  Email: {{schoolEmail}}', alignment: 'center', size: 10 },
    { type: 'spacer' },
    { type: 'heading', text: 'STUDENT ADMISSION FORM', alignment: 'center', size: 16, bold: true, color: '#111827' },
    { type: 'paragraph', text: 'Academic Year {{academicYear}}', alignment: 'center', italic: true, size: 11 },
    { type: 'spacer' },
    { type: 'divider' },
    { type: 'spacer' },
    { type: 'heading', text: 'Section A: Student Information', level: 3, bold: true, color: '#6D28D9' },
    {
      type: 'table',
      rows: [
        ['1. Full Name of Student:', '{{studentName}}'],
        ['2. Date of Birth:', '{{dateOfBirth}}'],
        ['3. Gender:', '{{gender}}'],
        ['4. Nationality:', '{{nationality}}'],
        ['5. CNIC / B-Form Number:', '{{cnic}}'],
        ['6. Blood Group:', '{{bloodGroup}}'],
        ['7. Religion:', '{{religion}}'],
        ['8. Mother Tongue:', '{{motherTongue}}'],
      ],
    },
    { type: 'spacer' },
    { type: 'heading', text: 'Section B: Parent / Guardian Information', level: 3, bold: true, color: '#6D28D9' },
    {
      type: 'table',
      rows: [
        ['9. Father\'s Name:', '{{fatherName}}'],
        ['10. Father\'s Occupation:', '{{fatherOccupation}}'],
        ['11. Father\'s CNIC:', '{{fatherCnic}}'],
        ['12. Mother\'s Name:', '{{motherName}}'],
        ['13. Mother\'s Occupation:', '{{motherOccupation}}'],
        ['14. Primary Contact Number:', '{{primaryContact}}'],
        ['15. Email Address:', '{{email}}'],
      ],
    },
    { type: 'spacer' },
    { type: 'heading', text: 'Section C: Address', level: 3, bold: true, color: '#6D28D9' },
    {
      type: 'table',
      rows: [
        ['16. Residential Address:', '{{address}}'],
        ['17. City:', '{{city}}'],
        ['18. Province / State:', '{{province}}'],
        ['19. Postal Code:', '{{postalCode}}'],
      ],
    },
    { type: 'spacer' },
    { type: 'heading', text: 'Section D: Previous Education', level: 3, bold: true, color: '#6D28D9' },
    {
      type: 'table',
      rows: [
        ['20. Last School Attended:', '{{lastSchool}}'],
        ['21. Class Completed:', '{{lastClass}}'],
        ['22. Percentage / Grade:', '{{lastGrade}}'],
        ['23. Year of Completion:', '{{lastYear}}'],
      ],
    },
    { type: 'spacer' },
    { type: 'heading', text: 'Section E: Admission Details', level: 3, bold: true, color: '#6D28D9' },
    {
      type: 'table',
      rows: [
        ['24. Class Applying For:', '{{applyingFor}}'],
        ['25. Transport Required:', '{{transport}}'],
        ['26. Hostel Required:', '{{hostel}}'],
      ],
    },
    { type: 'spacer' },
    { type: 'paragraph', text: 'Declaration: I hereby declare that the information provided above is true and correct to the best of my knowledge.' },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'paragraph', text: '_____________________              _____________________' },
    { type: 'paragraph', text: 'Parent/Guardian Signature        Date', italic: true, size: 10 },
  ],
};

// ============================================================
// 16. TRANSFER CERTIFICATE
// ============================================================
const transferCertificate: DocTemplate = {
  id: 'transfer-certificate',
  name: 'Transfer Certificate',
  category: 'school',
  description: 'School leaving / transfer certificate for students',
  keywords: ['transfer certificate', 'school leaving', 'tc', 'leaving certificate'],
  fileName: 'Transfer_Certificate.docx',
  sections: [
    { type: 'logo-placeholder', alignment: 'center' },
    { type: 'spacer' },
    { type: 'heading', text: '{{schoolName}}', alignment: 'center', size: 20, color: '#6D28D9' },
    { type: 'paragraph', text: '{{schoolAddress}}', alignment: 'center', size: 10 },
    { type: 'paragraph', text: 'Affiliated with {{affiliation}}', alignment: 'center', italic: true, size: 9 },
    { type: 'spacer' },
    { type: 'heading', text: 'TRANSFER CERTIFICATE', alignment: 'center', size: 18, bold: true, color: '#111827' },
    { type: 'paragraph', text: '(School Leaving Certificate)', alignment: 'center', italic: true, size: 11 },
    { type: 'spacer' },
    { type: 'divider' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'Certificate No: {{certificateNumber}}', bold: true, alignment: 'right' },
    { type: 'paragraph', text: 'Date of Issue: {{date}}', alignment: 'right' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'This is to certify that the following student has been a bonafide student of this institution and is hereby granted transfer certificate on request of the parent/guardian.' },
    { type: 'spacer' },
    {
      type: 'table',
      rows: [
        ['1. Name of Student', '{{studentName}}'],
        ['2. Father\'s Name', '{{fatherName}}'],
        ['3. Mother\'s Name', '{{motherName}}'],
        ['4. Date of Birth', '{{dateOfBirth}}'],
        ['5. Admission Number', '{{admissionNumber}}'],
        ['6. Date of Admission', '{{dateOfAdmission}}'],
        ['7. Class at Time of Leaving', '{{className}}'],
        ['8. Date of Leaving', '{{dateOfLeaving}}'],
        ['9. Reason for Leaving', '{{reason}}'],
        ['10. Last Exam Passed', '{{lastExam}}'],
        ['11. Conduct', '{{conduct}}'],
        ['12. Dues Cleared', '{{duesCleared}}'],
        ['13. Any Other Remarks', '{{remarks}}'],
      ],
    },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'This certificate is issued as per the school records. The student has cleared all dues and returned all school property.' },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'paragraph', text: '_____________________              _____________________', alignment: 'center' },
    { type: 'paragraph', text: 'Class Teacher                              Principal', alignment: 'center', italic: true, size: 10 },
    { type: 'spacer' },
    { type: 'paragraph', text: '(School Seal)', alignment: 'center', italic: true, size: 10 },
  ],
};

// ============================================================
// 17. CHARACTER CERTIFICATE
// ============================================================
const characterCertificate: DocTemplate = {
  id: 'character-certificate',
  name: 'Character Certificate',
  category: 'school',
  description: 'Student character and conduct certificate',
  keywords: ['character certificate', 'conduct certificate', 'character'],
  fileName: 'Character_Certificate.docx',
  sections: [
    { type: 'logo-placeholder', alignment: 'center' },
    { type: 'spacer' },
    { type: 'heading', text: '{{schoolName}}', alignment: 'center', size: 20, color: '#6D28D9' },
    { type: 'paragraph', text: '{{schoolAddress}}', alignment: 'center', size: 10 },
    { type: 'spacer' },
    { type: 'heading', text: 'CHARACTER CERTIFICATE', alignment: 'center', size: 20, bold: true, color: '#111827' },
    { type: 'spacer' },
    { type: 'divider' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'Certificate No: {{certificateNumber}}', bold: true, alignment: 'right' },
    { type: 'paragraph', text: 'Date of Issue: {{date}}', alignment: 'right' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'TO WHOM IT MAY CONCERN', alignment: 'center', bold: true, size: 12 },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'This is to certify that {{studentName}}, son/daughter of {{fatherName}}, was a student of this institution from {{startDate}} to {{endDate}}. During this period, he/she was a student of Class {{className}}.' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'During his/her stay at our institution, we found him/her to be a student of {{conduct}} moral character and conduct. He/she was respectful towards teachers, cooperative with fellow students, and actively participated in both academic and co-curricular activities.' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'His/her behavior throughout the period of study was exemplary, and he/she was never involved in any disciplinary issue. We wish him/her all the best for future endeavors.' },
    { type: 'spacer' },
    { type: 'spacer' },
    {
      type: 'table',
      rows: [
        ['Student Name:', '{{studentName}}'],
        ['Father\'s Name:', '{{fatherName}}'],
        ['Class Last Attended:', '{{className}}'],
        ['Period of Study:', '{{startDate}} – {{endDate}}'],
        ['Overall Conduct:', '{{conduct}}'],
        ['Disciplinary Record:', '{{disciplinaryRecord}}'],
      ],
    },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'paragraph', text: '_____________________              _____________________', alignment: 'center' },
    { type: 'paragraph', text: 'Class Teacher                              Principal', alignment: 'center', italic: true, size: 10 },
    { type: 'spacer' },
    { type: 'paragraph', text: '(School Seal)', alignment: 'center', italic: true, size: 10 },
  ],
};

// ============================================================
// 18. BONAFIDE CERTIFICATE
// ============================================================
const bonafideCertificate: DocTemplate = {
  id: 'bonafide',
  name: 'Bonafide Certificate',
  category: 'school',
  description: 'Certificate confirming a student is enrolled in the school',
  keywords: ['bonafide', 'bonafide certificate', 'enrollment certificate'],
  fileName: 'Bonafide_Certificate.docx',
  sections: [
    { type: 'logo-placeholder', alignment: 'center' },
    { type: 'spacer' },
    { type: 'heading', text: '{{schoolName}}', alignment: 'center', size: 20, color: '#6D28D9' },
    { type: 'paragraph', text: '{{schoolAddress}}', alignment: 'center', size: 10 },
    { type: 'spacer' },
    { type: 'heading', text: 'BONAFIDE CERTIFICATE', alignment: 'center', size: 20, bold: true, color: '#111827' },
    { type: 'spacer' },
    { type: 'divider' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'Certificate No: {{certificateNumber}}', bold: true, alignment: 'right' },
    { type: 'paragraph', text: 'Date of Issue: {{date}}', alignment: 'right' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'This is to certify that {{studentName}}, son/daughter of {{fatherName}}, is a bonafide student of {{schoolName}}, currently studying in Class {{className}} during the academic session {{session}}.' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'This certificate is being issued on the request of the student/parent for the purpose of {{purpose}}.' },
    { type: 'spacer' },
    {
      type: 'table',
      rows: [
        ['Student Name:', '{{studentName}}'],
        ['Father\'s Name:', '{{fatherName}}'],
        ['Date of Birth:', '{{dateOfBirth}}'],
        ['Admission Number:', '{{admissionNumber}}'],
        ['Current Class:', '{{className}}'],
        ['Academic Session:', '{{session}}'],
        ['Enrollment Status:', 'Currently Enrolled — Active'],
      ],
    },
    { type: 'spacer' },
    { type: 'paragraph', text: 'We confirm that the student is attending regular classes at our institution as of the date of this certificate.' },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'paragraph', text: '_____________________              _____________________', alignment: 'center' },
    { type: 'paragraph', text: 'Class Teacher                              Principal', alignment: 'center', italic: true, size: 10 },
    { type: 'spacer' },
    { type: 'paragraph', text: '(School Seal)', alignment: 'center', italic: true, size: 10 },
  ],
};

// ============================================================
// 19. FEE RECEIPT
// ============================================================
const feeReceipt: DocTemplate = {
  id: 'fee-receipt',
  name: 'Fee Receipt',
  category: 'school',
  description: 'Student fee payment receipt',
  keywords: ['fee receipt', 'receipt', 'payment receipt', 'school fee'],
  fileName: 'Fee_Receipt.docx',
  sections: [
    { type: 'logo-placeholder', alignment: 'center' },
    { type: 'spacer' },
    { type: 'heading', text: '{{schoolName}}', alignment: 'center', size: 18, color: '#6D28D9' },
    { type: 'paragraph', text: '{{schoolAddress}}  •  {{schoolPhone}}', alignment: 'center', size: 10 },
    { type: 'spacer' },
    { type: 'heading', text: 'FEE PAYMENT RECEIPT', alignment: 'center', size: 14, bold: true, color: '#111827' },
    { type: 'spacer' },
    { type: 'divider' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'Receipt No: {{receiptNumber}}', bold: true, alignment: 'right' },
    { type: 'paragraph', text: 'Date: {{date}}', alignment: 'right' },
    { type: 'spacer' },
    {
      type: 'table',
      rows: [
        ['Student Name:', '{{studentName}}'],
        ['Father\'s Name:', '{{fatherName}}'],
        ['Class:', '{{className}}'],
        ['Roll Number:', '{{rollNumber}}'],
        ['Academic Session:', '{{session}}'],
        ['Payment For:', '{{paymentFor}}'],
      ],
    },
    { type: 'spacer' },
    { type: 'heading', text: 'Fee Details', level: 3, bold: true, color: '#6D28D9' },
    {
      type: 'table',
      rows: [
        ['Particulars', 'Amount'],
        ['{{feeHead1}}', '{{feeAmount1}}'],
        ['{{feeHead2}}', '{{feeAmount2}}'],
        ['{{feeHead3}}', '{{feeAmount3}}'],
        ['{{feeHead4}}', '{{feeAmount4}}'],
        ['Subtotal:', '{{subtotal}}'],
        ['Previous Balance:', '{{previousBalance}}'],
        ['Discount:', '{{discount}}'],
        ['Late Fine:', '{{lateFine}}'],
        ['TOTAL PAID:', '{{total}}'],
      ],
    },
    { type: 'spacer' },
    { type: 'heading', text: 'Payment Information', level: 3, bold: true, color: '#6D28D9' },
    {
      type: 'table',
      rows: [
        ['Payment Method:', '{{paymentMethod}}'],
        ['Received By:', '{{receivedBy}}'],
        ['Amount in Words:', '{{amountInWords}}'],
        ['Balance Remaining:', '{{balanceRemaining}}'],
      ],
    },
    { type: 'spacer' },
    { type: 'paragraph', text: 'Thank you for your prompt payment.', alignment: 'center', italic: true },
    { type: 'spacer' },
    { type: 'paragraph', text: '_____________________              _____________________', alignment: 'center' },
    { type: 'paragraph', text: 'Cashier Signature                        School Stamp', alignment: 'center', italic: true, size: 10 },
  ],
};

// ============================================================
// 20. REFERENCE LETTER
// ============================================================
const referenceLetter: DocTemplate = {
  id: 'reference-letter',
  name: 'Reference Letter',
  category: 'personal',
  description: 'Professional reference letter for job or academic purposes',
  keywords: ['reference letter', 'recommendation letter', 'reference'],
  fileName: 'Reference_Letter.docx',
  sections: [
    { type: 'paragraph', text: '{{companyName}}', bold: true, size: 14 },
    { type: 'paragraph', text: '{{companyAddress}}' },
    { type: 'paragraph', text: 'Phone: {{companyPhone}}  |  Email: {{companyEmail}}' },
    { type: 'spacer' },
    { type: 'divider' },
    { type: 'spacer' },
    { type: 'paragraph', text: '{{date}}' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'To Whom It May Concern,' },
    { type: 'spacer' },
    { type: 'heading', text: 'Re: Reference for {{employeeName}}', level: 3, bold: true },
    { type: 'spacer' },
    { type: 'paragraph', text: 'I am pleased to write this letter of reference for {{employeeName}}, who worked under my supervision as a {{jobTitle}} at {{companyName}} from {{startDate}} to {{endDate}}.' },
    { type: 'spacer' },
    { type: 'paragraph', text: '{{bodyParagraphs}}' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'I recommend {{employeeName}} without any reservations. He/She would be a valuable asset to any organization. Please feel free to contact me if you need any additional information.' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'Sincerely,' },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'paragraph', text: '{{senderName}}', bold: true },
    { type: 'paragraph', text: '{{senderTitle}}' },
    { type: 'paragraph', text: '{{companyName}}' },
    { type: 'paragraph', text: 'Email: {{senderEmail}}  |  Phone: {{senderPhone}}' },
  ],
};

// ============================================================
// 21. RESIGNATION LETTER
// ============================================================
const resignationLetter: DocTemplate = {
  id: 'resignation-letter',
  name: 'Resignation Letter',
  category: 'personal',
  description: 'Professional resignation letter for job separation',
  keywords: ['resignation', 'resignation letter', 'resign', 'notice letter'],
  fileName: 'Resignation_Letter.docx',
  sections: [
    { type: 'paragraph', text: '{{fullName}}', bold: true, size: 13 },
    { type: 'paragraph', text: '{{address}}' },
    { type: 'paragraph', text: '{{email}} | {{phone}}' },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'paragraph', text: '{{date}}' },
    { type: 'spacer' },
    { type: 'paragraph', text: '{{managerName}}' },
    { type: 'paragraph', text: '{{managerTitle}}' },
    { type: 'paragraph', text: '{{companyName}}' },
    { type: 'paragraph', text: '{{companyAddress}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'Re: Resignation from Position of {{jobTitle}}', level: 3, bold: true },
    { type: 'spacer' },
    { type: 'paragraph', text: 'Dear {{managerName}},' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'I am writing to formally resign from my position as {{jobTitle}} at {{companyName}}, effective {{lastWorkingDay}}. This decision was not an easy one, as my time here has been both personally and professionally rewarding.' },
    { type: 'spacer' },
    { type: 'paragraph', text: '{{bodyParagraphs}}' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'I wish {{companyName}} and all my colleagues continued success. I hope our paths cross again in the future.' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'Thank you for the support and guidance you have provided during my tenure.' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'Sincerely,' },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'paragraph', text: '{{fullName}}', bold: true },
  ],
};

// ============================================================
// 22. EXPERIENCE LETTER
// ============================================================
const experienceLetter: DocTemplate = {
  id: 'experience-letter',
  name: 'Experience Letter',
  category: 'personal',
  description: 'Work experience certificate for employees',
  keywords: ['experience letter', 'work experience', 'employment certificate'],
  fileName: 'Experience_Letter.docx',
  sections: [
    { type: 'logo-placeholder', alignment: 'center' },
    { type: 'spacer' },
    { type: 'heading', text: '{{companyName}}', alignment: 'center', size: 20, color: '#6D28D9' },
    { type: 'paragraph', text: '{{companyAddress}}', alignment: 'center', size: 10 },
    { type: 'paragraph', text: 'Phone: {{companyPhone}}  |  Email: {{companyEmail}}', alignment: 'center', size: 10 },
    { type: 'spacer' },
    { type: 'heading', text: 'EXPERIENCE CERTIFICATE', alignment: 'center', size: 16, bold: true, color: '#111827' },
    { type: 'spacer' },
    { type: 'divider' },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'Ref No: {{refNumber}}', bold: true, alignment: 'right' },
    { type: 'paragraph', text: 'Date: {{date}}', alignment: 'right' },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'TO WHOM IT MAY CONCERN', alignment: 'center', bold: true },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'This is to certify that {{employeeName}} was employed with {{companyName}} from {{dateOfJoining}} to {{dateOfLeaving}}. During this period, he/she served as a {{designation}} in the {{department}} Department.' },
    { type: 'spacer' },
    { type: 'heading', text: 'Employment Details', level: 3, bold: true, color: '#6D28D9' },
    {
      type: 'table',
      rows: [
        ['Employee Name:', '{{employeeName}}'],
        ['Designation:', '{{designation}}'],
        ['Department:', '{{department}}'],
        ['Employee ID:', '{{employeeId}}'],
        ['Date of Joining:', '{{dateOfJoining}}'],
        ['Date of Leaving:', '{{dateOfLeaving}}'],
        ['Employment Type:', '{{employmentType}}'],
        ['Reporting Manager:', '{{reportingManager}}'],
      ],
    },
    { type: 'spacer' },
    { type: 'heading', text: 'Key Responsibilities', level: 3, bold: true, color: '#6D28D9' },
    { type: 'paragraph', text: '{{responsibilities}}' },
    { type: 'spacer' },
    { type: 'heading', text: 'Performance & Conduct', level: 3, bold: true, color: '#6D28D9' },
    { type: 'paragraph', text: '{{performance}}' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'We wish him/her continued success in all future endeavors.' },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'paragraph', text: 'For {{companyName}},' },
    { type: 'spacer' },
    { type: 'spacer' },
    { type: 'paragraph', text: '_____________________' },
    { type: 'paragraph', text: '{{senderName}}', bold: true },
    { type: 'paragraph', text: '{{senderTitle}}' },
    { type: 'spacer' },
    { type: 'paragraph', text: '(Company Seal)', italic: true, size: 9 },
  ],
};

// ============================================================
// EXPORT ALL TEMPLATES
// ============================================================
export const docTemplates: DocTemplate[] = [
  invoice,
  businessProposal,
  meetingMinutes,
  atsResume,
  modernResume,
  europassCV,
  coverLetter,
  purchaseOrder,
  quotation,
  companyLetterhead,
  contractAgreement,
  studentIdCard,
  reportCard,
  certificateAchievement,
  admissionForm,
  transferCertificate,
  characterCertificate,
  bonafideCertificate,
  feeReceipt,
  referenceLetter,
  resignationLetter,
  experienceLetter,
];

// ============================================================
// FIND TEMPLATE — keyword matching
// ============================================================
export function findDocTemplate(prompt: string): DocTemplate | null {
  const lower = prompt.toLowerCase();
  let best: DocTemplate | null = null;
  let score = 0;

  docTemplates.forEach((t) => {
    let s = 0;
    t.keywords.forEach((k) => {
      if (lower.includes(k.toLowerCase())) s += k.length;
    });
    if (s > score) {
      score = s;
      best = t;
    }
  });

  return best;
}