// ============================================================
// TEMPLATES — 15 ready-made Excel templates with rich sample data
// ============================================================

export type TemplateCategory = 'business' | 'personal' | 'education' | 'project';

export interface TemplateColumn {
  header: string;
  width?: number;
  type?: 'text' | 'number' | 'currency' | 'date' | 'formula' | 'percentage';
  formula?: (rowNum: number) => string;
  align?: 'left' | 'center' | 'right';
}

export interface TemplateSummaryRow {
  label: string;
  value: string;
}

export interface Template {
  id: string;
  name: string;
  category: TemplateCategory;
  description: string;
  keywords: string[];
  columns: TemplateColumn[];
  summaryTitle?: string;
  summary: TemplateSummaryRow[];
  instructions: string[];
  defaultRows: number;
  sampleData: any[][];
  fileName: string;
}

// ============================================================
// 1. SALES REPORT
// ============================================================
const salesReport: Template = {
  id: 'sales-report',
  name: 'Sales Report',
  category: 'business',
  description: 'Professional sales report with automatic tax and total',
  keywords: ['sales report', 'sales sheet', 'sales tracker', 'sale report', 'sales banao', 'sales'],
  defaultRows: 20,
  fileName: 'Sales_Report.xlsx',
  columns: [
    { header: 'Date', width: 13, type: 'formula', align: 'center', formula: (r) => (r === 2 ? `=TODAY()` : `=A${r - 1}+1`) },
    { header: 'Invoice #', width: 12, type: 'text', align: 'center' },
    { header: 'Product', width: 18, type: 'text' },
    { header: 'Customer', width: 20, type: 'text' },
    { header: 'Quantity', width: 10, type: 'number', align: 'center' },
    { header: 'Unit Price', width: 12, type: 'currency', align: 'right' },
    { header: 'Subtotal', width: 12, type: 'formula', align: 'right', formula: (r) => `=E${r}*F${r}` },
    { header: 'Tax (10%)', width: 12, type: 'formula', align: 'right', formula: (r) => `=G${r}*0.1` },
    { header: 'Total', width: 12, type: 'formula', align: 'right', formula: (r) => `=G${r}+H${r}` },
  ],
  summaryTitle: 'Sales Summary',
  summary: [
    { label: 'Total Sales (before tax)', value: '=SUM(G2:G{n})' },
    { label: 'Total Tax Collected', value: '=SUM(H2:H{n})' },
    { label: 'Grand Total Revenue', value: '=SUM(I2:I{n})' },
    { label: 'Total Orders', value: '=COUNTA(A2:A{n})' },
    { label: 'Average Order Value', value: '=IFERROR(AVERAGE(I2:I{n}),0)' },
    { label: 'Highest Sale', value: '=IFERROR(MAX(I2:I{n}),0)' },
    { label: 'Lowest Sale', value: '=IFERROR(MIN(I2:I{n}),0)' },
  ],
  instructions: [
    'HOW TO USE THIS SALES REPORT',
    '',
    '1. Enter sales data starting from Row 2.',
    '2. Date column fills automatically (today + 1 day per row).',
    '3. Columns C-F: manual entry.',
    '4. Columns G-I: auto-calculated (do not edit).',
    '5. Summary sheet updates automatically.',
    '',
    'FORMULAS:',
    '• Subtotal = Quantity × Unit Price',
    '• Tax = Subtotal × 10%',
    '• Total = Subtotal + Tax',
    '',
    'Generated by PDFplayOfficial AI Workspace',
    'https://pdfplayofficial.com',
  ],
  sampleData: [
    ['', 'INV-001', 'Widget A', 'Acme Corp', 10, 25.0],
    ['', 'INV-002', 'Widget B', 'Tech Solutions', 5, 40.0],
    ['', 'INV-003', 'Widget C', 'Global Traders', 20, 15.5],
    ['', 'INV-004', 'Widget D', 'Prime Industries', 8, 30.0],
    ['', 'INV-005', 'Widget E', 'Delta Corp', 15, 22.0],
    ['', 'INV-006', 'Widget F', 'Omega Ltd', 12, 18.0],
    ['', 'INV-007', 'Widget G', 'Sigma Inc', 25, 12.0],
    ['', 'INV-008', 'Widget H', 'Alpha Co', 6, 45.0],
    ['', 'INV-009', 'Widget I', 'Beta Systems', 18, 20.0],
    ['', 'INV-010', 'Widget J', 'Gamma Corp', 9, 35.0],
  ],
};

// ============================================================
// 2. INVOICE
// ============================================================
const invoice: Template = {
  id: 'invoice',
  name: 'Invoice',
  category: 'business',
  description: 'Professional invoice with line items and automatic totals',
  keywords: ['invoice', 'invoice banao', 'bill', 'billing', 'invoice sheet'],
  defaultRows: 20,
  fileName: 'Invoice.xlsx',
  columns: [
    { header: 'Item #', width: 10, type: 'number', align: 'center' },
    { header: 'Description', width: 35, type: 'text' },
    { header: 'Quantity', width: 12, type: 'number', align: 'center' },
    { header: 'Unit Price', width: 14, type: 'currency', align: 'right' },
    { header: 'Amount', width: 16, type: 'formula', align: 'right', formula: (r) => `=C${r}*D${r}` },
  ],
  summaryTitle: 'Invoice Summary',
  summary: [
    { label: 'Subtotal', value: '=SUM(E2:E{n})' },
    { label: 'Tax Rate', value: '10%' },
    { label: 'Tax Amount', value: '=SUM(E2:E{n})*0.1' },
    { label: 'Discount', value: '0' },
    { label: 'Total Due', value: '=SUM(E2:E{n})+SUM(E2:E{n})*0.1' },
  ],
  instructions: [
    'HOW TO USE THIS INVOICE',
    '',
    '1. Add line items starting from Row 2.',
    '2. Amount column calculates automatically.',
    '',
    'FORMULAS:',
    '• Amount = Quantity × Unit Price',
    '• Total Due = Subtotal + Tax − Discount',
    '',
    'Generated by PDFplayOfficial AI Workspace',
    'https://pdfplayofficial.com',
  ],
  sampleData: [
    [1, 'Website Design Services', 1, 1500.0],
    [2, 'Logo Design & Branding', 1, 300.0],
    [3, 'Hosting Setup (1 year)', 1, 200.0],
    [4, 'Domain Registration', 1, 15.0],
    [5, 'SEO Optimization', 1, 500.0],
    [6, 'Content Writing (5 pages)', 5, 80.0],
    [7, 'Social Media Setup', 1, 250.0],
    [8, 'Email Marketing Setup', 1, 180.0],
    [9, 'Analytics Installation', 1, 100.0],
    [10, 'Maintenance (monthly)', 1, 200.0],
  ],
};

// ============================================================
// 3. EXPENSE TRACKER
// ============================================================
const expenseTracker: Template = {
  id: 'expense-tracker',
  name: 'Expense Tracker',
  category: 'business',
  description: 'Track monthly expenses with categories and running totals',
  keywords: ['expense tracker', 'expense sheet', 'expenses', 'kharcha', 'monthly expenses'],
  defaultRows: 20,
  fileName: 'Expense_Tracker.xlsx',
  columns: [
    { header: 'Date', width: 13, type: 'formula', align: 'center', formula: (r) => (r === 2 ? `=TODAY()` : `=A${r - 1}+1`) },
    { header: 'Category', width: 18, type: 'text' },
    { header: 'Description', width: 30, type: 'text' },
    { header: 'Payment Method', width: 16, type: 'text', align: 'center' },
    { header: 'Amount', width: 14, type: 'currency', align: 'right' },
    { header: 'Cumulative', width: 14, type: 'formula', align: 'right', formula: (r) => (r === 2 ? `=E2` : `=F${r - 1}+E${r}`) },
  ],
  summaryTitle: 'Expense Summary',
  summary: [
    { label: 'Total Expenses', value: '=SUM(E2:E{n})' },
    { label: 'Average Expense', value: '=IFERROR(AVERAGE(E2:E{n}),0)' },
    { label: 'Highest Expense', value: '=IFERROR(MAX(E2:E{n}),0)' },
    { label: 'Lowest Expense', value: '=IFERROR(MIN(E2:E{n}),0)' },
    { label: 'Number of Transactions', value: '=COUNTA(A2:A{n})' },
  ],
  instructions: [
    'HOW TO USE THIS EXPENSE TRACKER',
    '',
    '1. Enter each expense starting from Row 2.',
    '2. Date column fills automatically.',
    '3. Cumulative column shows running total automatically.',
    '',
    'CATEGORIES: Office Rent, Utilities, Salaries, Marketing, Travel, Software, Equipment, Misc.',
    'PAYMENT: Cash, Credit Card, Bank Transfer, Cheque',
    '',
    'Generated by PDFplayOfficial AI Workspace',
    'https://pdfplayofficial.com',
  ],
  sampleData: [
    ['', 'Office Rent', 'January office rent', 'Bank Transfer', 1500.0],
    ['', 'Software', 'Adobe Creative Cloud', 'Credit Card', 60.0],
    ['', 'Marketing', 'Facebook Ads Campaign', 'Credit Card', 500.0],
    ['', 'Utilities', 'Electricity bill', 'Bank Transfer', 180.0],
    ['', 'Travel', 'Client meeting - taxi', 'Cash', 45.0],
    ['', 'Office Supplies', 'Printer ink & paper', 'Cash', 85.0],
    ['', 'Software', 'Slack subscription', 'Credit Card', 15.0],
    ['', 'Marketing', 'Google Ads', 'Credit Card', 350.0],
    ['', 'Utilities', 'Internet bill', 'Bank Transfer', 90.0],
    ['', 'Equipment', 'Wireless keyboard', 'Credit Card', 75.0],
  ],
};

// ============================================================
// 4. INVENTORY TRACKER
// ============================================================
const inventoryTracker: Template = {
  id: 'inventory-tracker',
  name: 'Inventory Tracker',
  category: 'business',
  description: 'Track stock levels with automatic reorder alerts',
  keywords: ['inventory', 'inventory tracker', 'stock', 'stock sheet', 'warehouse'],
  defaultRows: 20,
  fileName: 'Inventory_Tracker.xlsx',
  columns: [
    { header: 'SKU', width: 14, type: 'text', align: 'center' },
    { header: 'Product Name', width: 26, type: 'text' },
    { header: 'Category', width: 16, type: 'text' },
    { header: 'Unit Cost', width: 12, type: 'currency', align: 'right' },
    { header: 'Current Stock', width: 14, type: 'number', align: 'center' },
    { header: 'Reorder Level', width: 14, type: 'number', align: 'center' },
    { header: 'Stock Value', width: 14, type: 'formula', align: 'right', formula: (r) => `=D${r}*E${r}` },
    { header: 'Status', width: 16, type: 'formula', align: 'center', formula: (r) => `=IF(E${r}=0,"OUT OF STOCK",IF(E${r}<=F${r},"REORDER","OK"))` },
  ],
  summaryTitle: 'Inventory Summary',
  summary: [
    { label: 'Total Inventory Value', value: '=SUM(G2:G{n})' },
    { label: 'Total SKUs', value: '=COUNTA(A2:A{n})' },
    { label: 'Total Units in Stock', value: '=SUM(E2:E{n})' },
    { label: 'Items Needing Reorder', value: '=COUNTIF(H2:H{n},"REORDER")' },
    { label: 'Items Out of Stock', value: '=COUNTIF(H2:H{n},"OUT OF STOCK")' },
  ],
  instructions: [
    'HOW TO USE THIS INVENTORY TRACKER',
    '',
    '1. Enter each product starting from Row 2.',
    '2. Status: OK, REORDER, OUT OF STOCK — auto-calculated.',
    '',
    'Generated by PDFplayOfficial AI Workspace',
    'https://pdfplayofficial.com',
  ],
  sampleData: [
    ['SKU-001', 'Wireless Mouse', 'Electronics', 15.0, 45, 20],
    ['SKU-002', 'USB Cable 1m', 'Accessories', 3.5, 120, 50],
    ['SKU-003', 'Keyboard Mechanical', 'Electronics', 45.0, 8, 15],
    ['SKU-004', 'Monitor 24"', 'Electronics', 180.0, 12, 5],
    ['SKU-005', 'Laptop Stand', 'Accessories', 25.0, 30, 10],
    ['SKU-006', 'Webcam HD', 'Electronics', 60.0, 0, 10],
    ['SKU-007', 'Headphones', 'Audio', 85.0, 22, 10],
    ['SKU-008', 'Desk Lamp', 'Office', 35.0, 15, 8],
    ['SKU-009', 'Notebook A5', 'Stationery', 5.0, 200, 50],
    ['SKU-010', 'Pen Pack', 'Stationery', 3.0, 18, 25],
  ],
};

// ============================================================
// 5. PROFIT & LOSS
// ============================================================
const profitLoss: Template = {
  id: 'profit-loss',
  name: 'Profit & Loss Statement',
  category: 'business',
  description: 'Standard P&L statement with revenue, costs, and net profit',
  keywords: ['profit and loss', 'profit loss', 'p&l', 'income statement', 'pl statement'],
  defaultRows: 20,
  fileName: 'Profit_Loss_Statement.xlsx',
  columns: [
    { header: 'Line Item', width: 28, type: 'text' },
    { header: 'Category', width: 16, type: 'text' },
    { header: 'Amount', width: 16, type: 'currency', align: 'right' },
    { header: 'Type', width: 14, type: 'formula', align: 'center', formula: (r) => `=IF(B${r}="Revenue","INCOME",IF(B${r}="COGS","COGS","EXPENSE"))` },
  ],
  summaryTitle: 'Financial Summary',
  summary: [
    { label: 'Total Revenue', value: '=SUMIF(B2:B{n},"Revenue",C2:C{n})' },
    { label: 'Cost of Goods Sold', value: '=SUMIF(B2:B{n},"COGS",C2:C{n})' },
    { label: 'Gross Profit', value: '=SUMIF(B2:B{n},"Revenue",C2:C{n})-SUMIF(B2:B{n},"COGS",C2:C{n})' },
    { label: 'Total Operating Expenses', value: '=SUMIF(B2:B{n},"Expense",C2:C{n})' },
    { label: 'Net Profit', value: '=SUMIF(B2:B{n},"Revenue",C2:C{n})-SUMIF(B2:B{n},"COGS",C2:C{n})-SUMIF(B2:B{n},"Expense",C2:C{n})' },
    { label: 'Profit Margin %', value: '=IFERROR((SUMIF(B2:B{n},"Revenue",C2:C{n})-SUMIF(B2:B{n},"COGS",C2:C{n})-SUMIF(B2:B{n},"Expense",C2:C{n}))/SUMIF(B2:B{n},"Revenue",C2:C{n}),0)' },
  ],
  instructions: [
    'HOW TO USE THIS P&L STATEMENT',
    '',
    '1. Add each financial line item starting from Row 2.',
    '2. Category must be: Revenue, COGS, or Expense.',
    '',
    'Generated by PDFplayOfficial AI Workspace',
    'https://pdfplayofficial.com',
  ],
  sampleData: [
    ['Product Sales', 'Revenue', 50000.0],
    ['Service Revenue', 'Revenue', 15000.0],
    ['Consulting Fees', 'Revenue', 8000.0],
    ['Cost of Materials', 'COGS', 20000.0],
    ['Manufacturing', 'COGS', 5000.0],
    ['Office Rent', 'Expense', 3000.0],
    ['Salaries', 'Expense', 12000.0],
    ['Marketing', 'Expense', 2500.0],
    ['Utilities', 'Expense', 800.0],
    ['Software', 'Expense', 600.0],
  ],
};

// ============================================================
// 6. PAYROLL SHEET
// ============================================================
const payrollSheet: Template = {
  id: 'payroll-sheet',
  name: 'Payroll Sheet',
  category: 'business',
  description: 'Monthly payroll with salary, allowances, deductions, and net pay',
  keywords: ['payroll', 'salary sheet', 'salary', 'wages', 'payroll sheet'],
  defaultRows: 20,
  fileName: 'Payroll_Sheet.xlsx',
  columns: [
    { header: 'Employee ID', width: 12, type: 'text', align: 'center' },
    { header: 'Employee Name', width: 22, type: 'text' },
    { header: 'Designation', width: 18, type: 'text' },
    { header: 'Basic Salary', width: 13, type: 'currency', align: 'right' },
    { header: 'Allowances', width: 12, type: 'currency', align: 'right' },
    { header: 'Deductions', width: 12, type: 'currency', align: 'right' },
    { header: 'Gross Pay', width: 13, type: 'formula', align: 'right', formula: (r) => `=D${r}+E${r}` },
    { header: 'Net Pay', width: 13, type: 'formula', align: 'right', formula: (r) => `=G${r}-F${r}` },
  ],
  summaryTitle: 'Payroll Summary',
  summary: [
    { label: 'Total Basic Salaries', value: '=SUM(D2:D{n})' },
    { label: 'Total Allowances', value: '=SUM(E2:E{n})' },
    { label: 'Total Deductions', value: '=SUM(F2:F{n})' },
    { label: 'Total Gross Pay', value: '=SUM(G2:G{n})' },
    { label: 'Total Net Pay', value: '=SUM(H2:H{n})' },
    { label: 'Total Employees', value: '=COUNTA(A2:A{n})' },
  ],
  instructions: [
    'HOW TO USE THIS PAYROLL SHEET',
    '',
    '1. Enter employee details starting from Row 2.',
    '2. Gross Pay and Net Pay calculate automatically.',
    '',
    'Generated by PDFplayOfficial AI Workspace',
    'https://pdfplayofficial.com',
  ],
  sampleData: [
    ['EMP-001', 'Ahmed Khan', 'Senior Manager', 5000.0, 1000.0, 500.0],
    ['EMP-002', 'Sara Ali', 'Senior Developer', 4500.0, 900.0, 450.0],
    ['EMP-003', 'Bilal Ahmed', 'UI/UX Designer', 3500.0, 600.0, 350.0],
    ['EMP-004', 'Fatima Hassan', 'Marketing Lead', 4000.0, 800.0, 400.0],
    ['EMP-005', 'Usman Tariq', 'Accountant', 3200.0, 500.0, 320.0],
    ['EMP-006', 'Ayesha Malik', 'HR Manager', 3800.0, 700.0, 380.0],
    ['EMP-007', 'Hassan Raza', 'Sales Executive', 2800.0, 1200.0, 280.0],
    ['EMP-008', 'Zainab Ahmed', 'Content Writer', 2500.0, 400.0, 250.0],
    ['EMP-009', 'Ali Raza', 'Junior Developer', 2200.0, 300.0, 220.0],
    ['EMP-010', 'Mariam Khan', 'Customer Support', 2000.0, 250.0, 200.0],
  ],
};

// ============================================================
// 7. CUSTOMER LIST (CRM)
// ============================================================
const customerList: Template = {
  id: 'customer-list',
  name: 'Customer List',
  category: 'business',
  description: 'Customer database with contact details and status',
  keywords: ['customer list', 'crm', 'customer database', 'client list', 'contacts', 'customer'],
  defaultRows: 20,
  fileName: 'Customer_List.xlsx',
  columns: [
    { header: 'Customer ID', width: 13, type: 'text', align: 'center' },
    { header: 'Full Name', width: 22, type: 'text' },
    { header: 'Email', width: 28, type: 'text' },
    { header: 'Phone', width: 16, type: 'text', align: 'center' },
    { header: 'Company', width: 20, type: 'text' },
    { header: 'City', width: 14, type: 'text' },
    { header: 'Status', width: 12, type: 'text', align: 'center' },
    { header: 'Monthly Value', width: 14, type: 'currency', align: 'right' },
  ],
  summaryTitle: 'CRM Summary',
  summary: [
    { label: 'Total Customers', value: '=COUNTA(A2:A{n})' },
    { label: 'Active Customers', value: '=COUNTIF(G2:G{n},"Active")' },
    { label: 'Inactive Customers', value: '=COUNTIF(G2:G{n},"Inactive")' },
    { label: 'Total Monthly Value', value: '=SUM(H2:H{n})' },
    { label: 'Average Monthly Value', value: '=IFERROR(AVERAGE(H2:H{n}),0)' },
  ],
  instructions: [
    'HOW TO USE THIS CUSTOMER LIST',
    '',
    '1. Enter each customer starting from Row 2.',
    '2. Status: Active, Inactive, Prospect, VIP.',
    '',
    'Generated by PDFplayOfficial AI Workspace',
    'https://pdfplayofficial.com',
  ],
  sampleData: [
    ['CUST-001', 'John Smith', 'john@acmecorp.com', '+1-555-0101', 'Acme Corp', 'New York', 'Active', 1200.0],
    ['CUST-002', 'Fatima Hassan', 'fatima@techsol.com', '+92-300-1234567', 'Tech Solutions', 'Karachi', 'Active', 800.0],
    ['CUST-003', 'Ravi Kumar', 'ravi@global.in', '+91-98765-43210', 'Global Traders', 'Mumbai', 'Prospect', 0],
    ['CUST-004', 'Sarah Johnson', 'sarah@primeind.com', '+1-555-0202', 'Prime Industries', 'Chicago', 'Active', 2500.0],
    ['CUST-005', 'Ahmed Al-Farsi', 'ahmed@deltacorp.ae', '+971-50-1234567', 'Delta Corp', 'Dubai', 'VIP', 5000.0],
    ['CUST-006', 'Emily Chen', 'emily@omega.sg', '+65-9123-4567', 'Omega Ltd', 'Singapore', 'Active', 1800.0],
    ['CUST-007', 'Hassan Raza', 'hassan@sigma.pk', '+92-321-9876543', 'Sigma Inc', 'Lahore', 'Active', 950.0],
    ['CUST-008', 'Maria Garcia', 'maria@alpha.es', '+34-612-345-678', 'Alpha Co', 'Madrid', 'Inactive', 0],
    ['CUST-009', 'David Kim', 'david@beta.kr', '+82-10-1234-5678', 'Beta Systems', 'Seoul', 'Active', 3200.0],
    ['CUST-010', 'Ayesha Malik', 'ayesha@gamma.pk', '+92-333-1111222', 'Gamma Corp', 'Islamabad', 'Prospect', 0],
  ],
};

// ============================================================
// 8. MONTHLY BUDGET
// ============================================================
const monthlyBudget: Template = {
  id: 'monthly-budget',
  name: 'Monthly Budget',
  category: 'personal',
  description: 'Track monthly budget vs actual spending by category',
  keywords: ['budget', 'monthly budget', 'budget planner', 'budget sheet', 'budget banao'],
  defaultRows: 20,
  fileName: 'Monthly_Budget.xlsx',
  columns: [
    { header: 'Category', width: 22, type: 'text' },
    { header: 'Budgeted', width: 14, type: 'currency', align: 'right' },
    { header: 'Actual', width: 14, type: 'currency', align: 'right' },
    { header: 'Difference', width: 14, type: 'formula', align: 'right', formula: (r) => `=B${r}-C${r}` },
    { header: 'Status', width: 12, type: 'formula', align: 'center', formula: (r) => `=IF(D${r}>0,"UNDER",IF(D${r}<0,"OVER","ON TARGET"))` },
    { header: '% Used', width: 12, type: 'formula', align: 'center', formula: (r) => `=IFERROR(C${r}/B${r},0)` },
  ],
  summaryTitle: 'Budget Summary',
  summary: [
    { label: 'Total Budgeted', value: '=SUM(B2:B{n})' },
    { label: 'Total Actual', value: '=SUM(C2:C{n})' },
    { label: 'Total Difference', value: '=SUM(D2:D{n})' },
    { label: 'Categories Over Budget', value: '=COUNTIF(E2:E{n},"OVER")' },
    { label: 'Categories Under Budget', value: '=COUNTIF(E2:E{n},"UNDER")' },
  ],
  instructions: [
    'HOW TO USE THIS MONTHLY BUDGET',
    '',
    '1. List each spending category starting from Row 2.',
    '2. Enter your budgeted amount and actual spending.',
    '3. Difference and % Used calculate automatically.',
    '',
    'Generated by PDFplayOfficial AI Workspace',
    'https://pdfplayofficial.com',
  ],
  sampleData: [
    ['Rent', 1500.0, 1500.0],
    ['Groceries', 600.0, 720.0],
    ['Utilities', 200.0, 180.0],
    ['Transport', 300.0, 250.0],
    ['Entertainment', 150.0, 200.0],
    ['Dining Out', 250.0, 320.0],
    ['Health & Fitness', 100.0, 80.0],
    ['Education', 200.0, 150.0],
    ['Savings', 500.0, 500.0],
    ['Miscellaneous', 200.0, 175.0],
  ],
};

// ============================================================
// 9. HABIT TRACKER
// ============================================================
const habitTracker: Template = {
  id: 'habit-tracker',
  name: 'Habit Tracker',
  category: 'personal',
  description: 'Track daily habits with monthly grid view',
  keywords: ['habit tracker', 'habits', 'habit sheet', 'daily tracker', 'habit banao'],
  defaultRows: 15,
  fileName: 'Habit_Tracker.xlsx',
  columns: [
    { header: 'Habit', width: 22, type: 'text' },
    { header: 'Day 1', width: 8, type: 'text', align: 'center' },
    { header: 'Day 2', width: 8, type: 'text', align: 'center' },
    { header: 'Day 3', width: 8, type: 'text', align: 'center' },
    { header: 'Day 4', width: 8, type: 'text', align: 'center' },
    { header: 'Day 5', width: 8, type: 'text', align: 'center' },
    { header: 'Day 6', width: 8, type: 'text', align: 'center' },
    { header: 'Day 7', width: 8, type: 'text', align: 'center' },
    { header: 'Total', width: 10, type: 'formula', align: 'center', formula: (r) => `=COUNTIF(B${r}:H${r},"✓")` },
    { header: 'Streak', width: 10, type: 'formula', align: 'center', formula: (r) => `=I${r}` },
  ],
  summaryTitle: 'Habit Summary',
  summary: [
    { label: 'Total Habits Tracked', value: '=COUNTA(A2:A{n})' },
    { label: 'Total Completions', value: '=SUM(I2:I{n})' },
    { label: 'Average Completion', value: '=IFERROR(AVERAGE(I2:I{n}),0)' },
  ],
  instructions: [
    'HOW TO USE THIS HABIT TRACKER',
    '',
    '1. List your habits starting from Row 2.',
    '2. Mark each day with "✓" for completed.',
    '',
    'Generated by PDFplayOfficial AI Workspace',
    'https://pdfplayofficial.com',
  ],
  sampleData: [
    ['Exercise 30 min', '✓', '✓', '✓', '', '✓', '', '✓'],
    ['Read 30 min', '✓', '✓', '', '✓', '✓', '✓', '✓'],
    ['Drink 8 glasses water', '✓', '✓', '✓', '✓', '✓', '✓', '✓'],
    ['Meditate 10 min', '✓', '', '✓', '✓', '', '✓', '✓'],
    ['No sugar', '', '✓', '✓', '', '✓', '✓', ''],
    ['Sleep by 11 PM', '✓', '✓', '✓', '✓', '', '✓', '✓'],
    ['No phone in bed', '✓', '', '✓', '✓', '✓', '', '✓'],
    ['Walk 10k steps', '✓', '✓', '', '✓', '✓', '✓', '✓'],
    ['Journal writing', '✓', '✓', '✓', '', '✓', '✓', '✓'],
    ['Learn new skill', '', '✓', '', '✓', '', '✓', '✓'],
  ],
};

// ============================================================
// 10. TO-DO LIST
// ============================================================
const todoList: Template = {
  id: 'todo-list',
  name: 'To-Do List',
  category: 'personal',
  description: 'Task list with priority and status tracking',
  keywords: ['todo', 'to do', 'task list', 'tasks', 'todo list', 'task banao'],
  defaultRows: 20,
  fileName: 'Todo_List.xlsx',
  columns: [
    { header: 'Task ID', width: 10, type: 'text', align: 'center' },
    { header: 'Task', width: 32, type: 'text' },
    { header: 'Priority', width: 10, type: 'text', align: 'center' },
    { header: 'Assignee', width: 16, type: 'text' },
    { header: 'Due Date', width: 13, type: 'date', align: 'center' },
    { header: 'Status', width: 13, type: 'text', align: 'center' },
    { header: 'Days Left', width: 12, type: 'formula', align: 'center', formula: (r) => `=IFERROR(E${r}-TODAY(),"")` },
  ],
  summaryTitle: 'Task Summary',
  summary: [
    { label: 'Total Tasks', value: '=COUNTA(A2:A{n})' },
    { label: 'Completed', value: '=COUNTIF(F2:F{n},"Done")' },
    { label: 'In Progress', value: '=COUNTIF(F2:F{n},"In Progress")' },
    { label: 'Pending', value: '=COUNTIF(F2:F{n},"Pending")' },
    { label: 'High Priority', value: '=COUNTIF(C2:C{n},"High")' },
  ],
  instructions: [
    'HOW TO USE THIS TO-DO LIST',
    '',
    '1. Add each task starting from Row 2.',
    '2. Priority: High, Medium, Low.',
    '3. Status: Pending, In Progress, Done.',
    '',
    'Generated by PDFplayOfficial AI Workspace',
    'https://pdfplayofficial.com',
  ],
  sampleData: [
    ['T-001', 'Review design mockups', 'High', 'Ahmed', '2025-02-01', 'In Progress'],
    ['T-002', 'Send client proposal', 'High', 'Sara', '2025-01-30', 'Pending'],
    ['T-003', 'Update documentation', 'Medium', 'Bilal', '2025-02-05', 'Done'],
    ['T-004', 'Fix login bug', 'High', 'Ahmed', '2025-02-02', 'In Progress'],
    ['T-005', 'Team standup meeting', 'Low', 'Fatima', '2025-02-03', 'Pending'],
    ['T-006', 'Code review PR #142', 'Medium', 'Hassan', '2025-02-04', 'Pending'],
    ['T-007', 'Write blog post', 'Low', 'Ayesha', '2025-02-08', 'Pending'],
    ['T-008', 'Prepare monthly report', 'High', 'Usman', '2025-02-06', 'Pending'],
    ['T-009', 'Update dependencies', 'Medium', 'Ali', '2025-02-07', 'Done'],
    ['T-010', 'Client onboarding call', 'High', 'Mariam', '2025-02-01', 'Done'],
  ],
};

// ============================================================
// 11. STUDENT MARKS SHEET
// ============================================================
const studentMarks: Template = {
  id: 'student-marks',
  name: 'Student Marks Sheet',
  category: 'education',
  description: 'Student marks with automatic totals and grades',
  keywords: ['student marks', 'marks sheet', 'students marks', 'exam result', 'marks banao', 'marks'],
  defaultRows: 20,
  fileName: 'Student_Marks_Sheet.xlsx',
  columns: [
    { header: 'Roll #', width: 10, type: 'number', align: 'center' },
    { header: 'Student Name', width: 22, type: 'text' },
    { header: 'Math', width: 10, type: 'number', align: 'center' },
    { header: 'Science', width: 10, type: 'number', align: 'center' },
    { header: 'English', width: 10, type: 'number', align: 'center' },
    { header: 'Urdu', width: 10, type: 'number', align: 'center' },
    { header: 'Islamiat', width: 10, type: 'number', align: 'center' },
    { header: 'Total', width: 12, type: 'formula', align: 'center', formula: (r) => `=SUM(C${r}:G${r})` },
    { header: '%', width: 10, type: 'formula', align: 'center', formula: (r) => `=IFERROR(H${r}/500*100,0)` },
    { header: 'Grade', width: 10, type: 'formula', align: 'center', formula: (r) => `=IF(I${r}>=90,"A+",IF(I${r}>=80,"A",IF(I${r}>=70,"B",IF(I${r}>=60,"C",IF(I${r}>=40,"D","F")))))` },
  ],
  summaryTitle: 'Class Summary',
  summary: [
    { label: 'Class Average %', value: '=IFERROR(AVERAGE(I2:I{n}),0)' },
    { label: 'Highest %', value: '=IFERROR(MAX(I2:I{n}),0)' },
    { label: 'Lowest %', value: '=IFERROR(MIN(I2:I{n}),0)' },
    { label: 'Pass Count', value: '=COUNTIF(I2:I{n},">=40")' },
    { label: 'Fail Count', value: '=COUNTIF(I2:I{n},"<40")' },
    { label: 'A+ Grade Count', value: '=COUNTIF(J2:J{n},"A+")' },
  ],
  instructions: [
    'HOW TO USE THIS MARKS SHEET',
    '',
    '1. Enter student marks starting from Row 2.',
    '2. Total, %, and Grade calculate automatically.',
    '',
    'GRADING SCALE:',
    'A+ = 90%+ | A = 80-89% | B = 70-79% | C = 60-69% | D = 40-59% | F = Below 40%',
    '',
    'Generated by PDFplayOfficial AI Workspace',
    'https://pdfplayofficial.com',
  ],
  sampleData: [
    [1, 'Ali Khan', 85, 90, 78, 82, 88],
    [2, 'Sara Ahmed', 92, 88, 95, 90, 85],
    [3, 'Bilal Raza', 68, 72, 65, 70, 75],
    [4, 'Fatima Malik', 95, 92, 90, 88, 94],
    [5, 'Usman Tariq', 72, 78, 80, 75, 70],
    [6, 'Ayesha Khan', 88, 85, 92, 90, 86],
    [7, 'Hassan Ali', 65, 68, 70, 62, 72],
    [8, 'Zainab Ahmed', 90, 94, 88, 92, 90],
    [9, 'Ahmed Raza', 78, 82, 75, 80, 78],
    [10, 'Mariam Hassan', 82, 88, 85, 84, 80],
  ],
};

// ============================================================
// 12. ATTENDANCE SHEET
// ============================================================
const attendanceSheet: Template = {
  id: 'attendance-sheet',
  name: 'Attendance Sheet',
  category: 'education',
  description: 'Monthly attendance with present/absent tracking',
  keywords: ['attendance', 'attendance sheet', 'attendance tracker', 'hazri', 'attendance banao'],
  defaultRows: 20,
  fileName: 'Attendance_Sheet.xlsx',
  columns: [
    { header: 'Roll #', width: 10, type: 'number', align: 'center' },
    { header: 'Student Name', width: 22, type: 'text' },
    { header: 'Day 1', width: 8, type: 'text', align: 'center' },
    { header: 'Day 2', width: 8, type: 'text', align: 'center' },
    { header: 'Day 3', width: 8, type: 'text', align: 'center' },
    { header: 'Day 4', width: 8, type: 'text', align: 'center' },
    { header: 'Day 5', width: 8, type: 'text', align: 'center' },
    { header: 'Present', width: 10, type: 'formula', align: 'center', formula: (r) => `=COUNTIF(C${r}:G${r},"P")` },
    { header: 'Absent', width: 10, type: 'formula', align: 'center', formula: (r) => `=COUNTIF(C${r}:G${r},"A")` },
    { header: '%', width: 10, type: 'formula', align: 'center', formula: (r) => `=IFERROR(H${r}/(H${r}+I${r})*100,0)` },
  ],
  summaryTitle: 'Attendance Summary',
  summary: [
    { label: 'Total Students', value: '=COUNTA(A2:A{n})' },
    { label: 'Total Present Days', value: '=SUM(H2:H{n})' },
    { label: 'Total Absent Days', value: '=SUM(I2:I{n})' },
    { label: 'Average Attendance %', value: '=IFERROR(AVERAGE(J2:J{n}),0)' },
  ],
  instructions: [
    'HOW TO USE THIS ATTENDANCE SHEET',
    '',
    '1. Enter student names starting from Row 2.',
    '2. Mark P for Present, A for Absent, L for Leave.',
    '',
    'Generated by PDFplayOfficial AI Workspace',
    'https://pdfplayofficial.com',
  ],
  sampleData: [
    [1, 'Ali Khan', 'P', 'P', 'A', 'P', 'P'],
    [2, 'Sara Ahmed', 'P', 'P', 'P', 'P', 'P'],
    [3, 'Bilal Raza', 'A', 'P', 'P', 'A', 'P'],
    [4, 'Fatima Malik', 'P', 'P', 'P', 'P', 'P'],
    [5, 'Usman Tariq', 'P', 'A', 'P', 'P', 'P'],
    [6, 'Ayesha Khan', 'P', 'P', 'P', 'P', 'A'],
    [7, 'Hassan Ali', 'A', 'A', 'P', 'P', 'P'],
    [8, 'Zainab Ahmed', 'P', 'P', 'P', 'P', 'P'],
    [9, 'Ahmed Raza', 'P', 'P', 'A', 'P', 'P'],
    [10, 'Mariam Hassan', 'P', 'P', 'P', 'A', 'P'],
  ],
};

// ============================================================
// 13. GRADE BOOK
// ============================================================
const gradeBook: Template = {
  id: 'grade-book',
  name: 'Grade Book',
  category: 'education',
  description: 'Grade book with assignments, quizzes, exams, and final grades',
  keywords: ['grade book', 'gradebook', 'grades', 'grading sheet', 'grade banao'],
  defaultRows: 20,
  fileName: 'Grade_Book.xlsx',
  columns: [
    { header: 'Student ID', width: 12, type: 'text', align: 'center' },
    { header: 'Student Name', width: 22, type: 'text' },
    { header: 'Assignments (20%)', width: 16, type: 'number', align: 'center' },
    { header: 'Quizzes (20%)', width: 13, type: 'number', align: 'center' },
    { header: 'Midterm (25%)', width: 13, type: 'number', align: 'center' },
    { header: 'Final Exam (35%)', width: 15, type: 'number', align: 'center' },
    { header: 'Weighted Total', width: 15, type: 'formula', align: 'center', formula: (r) => `=C${r}*0.2+D${r}*0.2+E${r}*0.25+F${r}*0.35` },
    { header: 'Letter Grade', width: 12, type: 'formula', align: 'center', formula: (r) => `=IF(G${r}>=90,"A",IF(G${r}>=80,"B",IF(G${r}>=70,"C",IF(G${r}>=60,"D","F"))))` },
  ],
  summaryTitle: 'Class Summary',
  summary: [
    { label: 'Class Average', value: '=IFERROR(AVERAGE(G2:G{n}),0)' },
    { label: 'Highest Score', value: '=IFERROR(MAX(G2:G{n}),0)' },
    { label: 'Lowest Score', value: '=IFERROR(MIN(G2:G{n}),0)' },
    { label: 'A Grades', value: '=COUNTIF(H2:H{n},"A")' },
    { label: 'B Grades', value: '=COUNTIF(H2:H{n},"B")' },
    { label: 'C Grades', value: '=COUNTIF(H2:H{n},"C")' },
    { label: 'F Grades', value: '=COUNTIF(H2:H{n},"F")' },
  ],
  instructions: [
    'HOW TO USE THIS GRADE BOOK',
    '',
    '1. Enter student scores (out of 100) for each category.',
    '2. Weighted Total and Letter Grade calculate automatically.',
    '',
    'WEIGHTS: Assignments = 20%, Quizzes = 20%, Midterm = 25%, Final = 35%',
    '',
    'Generated by PDFplayOfficial AI Workspace',
    'https://pdfplayofficial.com',
  ],
  sampleData: [
    ['STU-001', 'Ali Khan', 85, 90, 88, 82],
    ['STU-002', 'Sara Ahmed', 92, 88, 95, 90],
    ['STU-003', 'Bilal Raza', 68, 72, 65, 70],
    ['STU-004', 'Fatima Malik', 95, 92, 90, 88],
    ['STU-005', 'Usman Tariq', 72, 78, 80, 75],
    ['STU-006', 'Ayesha Khan', 88, 85, 92, 90],
    ['STU-007', 'Hassan Ali', 65, 68, 70, 62],
    ['STU-008', 'Zainab Ahmed', 90, 94, 88, 92],
    ['STU-009', 'Ahmed Raza', 78, 82, 75, 80],
    ['STU-010', 'Mariam Hassan', 82, 88, 85, 84],
  ],
};

// ============================================================
// 14. PROJECT TIMELINE
// ============================================================
const projectTimeline: Template = {
  id: 'project-timeline',
  name: 'Project Timeline',
  category: 'project',
  description: 'Track project tasks with start/end dates and progress',
  keywords: ['project timeline', 'timeline', 'project plan', 'timeline banao'],
  defaultRows: 20,
  fileName: 'Project_Timeline.xlsx',
  columns: [
    { header: 'Task ID', width: 10, type: 'text', align: 'center' },
    { header: 'Task Name', width: 28, type: 'text' },
    { header: 'Owner', width: 16, type: 'text' },
    { header: 'Start Date', width: 13, type: 'date', align: 'center' },
    { header: 'End Date', width: 13, type: 'date', align: 'center' },
    { header: 'Duration (days)', width: 14, type: 'formula', align: 'center', formula: (r) => `=IFERROR(E${r}-D${r},0)` },
    { header: 'Status', width: 13, type: 'text', align: 'center' },
    { header: 'Progress %', width: 12, type: 'percentage', align: 'center' },
  ],
  summaryTitle: 'Project Summary',
  summary: [
    { label: 'Total Tasks', value: '=COUNTA(A2:A{n})' },
    { label: 'Completed', value: '=COUNTIF(G2:G{n},"Done")' },
    { label: 'In Progress', value: '=COUNTIF(G2:G{n},"In Progress")' },
    { label: 'Not Started', value: '=COUNTIF(G2:G{n},"Not Started")' },
    { label: 'Average Progress', value: '=IFERROR(AVERAGE(H2:H{n}),0)' },
  ],
  instructions: [
    'HOW TO USE THIS PROJECT TIMELINE',
    '',
    '1. Add each task starting from Row 2.',
    '2. Duration calculates automatically from dates.',
    '3. Status: Not Started, In Progress, Done, Blocked.',
    '',
    'Generated by PDFplayOfficial AI Workspace',
    'https://pdfplayofficial.com',
  ],
  sampleData: [
    ['T-001', 'Requirements gathering', 'Ahmed', '2025-01-15', '2025-01-20', 'Done', 1.0],
    ['T-002', 'UI/UX Design', 'Sara', '2025-01-21', '2025-02-05', 'In Progress', 0.6],
    ['T-003', 'Backend Development', 'Bilal', '2025-02-06', '2025-03-15', 'Not Started', 0],
    ['T-004', 'Frontend Development', 'Hassan', '2025-02-06', '2025-03-20', 'Not Started', 0],
    ['T-005', 'Database Design', 'Usman', '2025-01-25', '2025-02-03', 'Done', 1.0],
    ['T-006', 'API Integration', 'Ali', '2025-03-01', '2025-03-25', 'Not Started', 0],
    ['T-007', 'Testing & QA', 'Fatima', '2025-03-20', '2025-04-05', 'Not Started', 0],
    ['T-008', 'Documentation', 'Ayesha', '2025-03-25', '2025-04-10', 'Not Started', 0],
    ['T-009', 'Deployment', 'Ahmed', '2025-04-10', '2025-04-15', 'Not Started', 0],
    ['T-010', 'Client Training', 'Mariam', '2025-04-15', '2025-04-20', 'Not Started', 0],
  ],
};

// ============================================================
// 15. TASK TRACKER
// ============================================================
const taskTracker: Template = {
  id: 'task-tracker',
  name: 'Task Tracker',
  category: 'project',
  description: 'Track team tasks with priority, assignee, and status',
  keywords: ['task tracker', 'tasks', 'team tasks', 'sprint tracker', 'task banao'],
  defaultRows: 20,
  fileName: 'Task_Tracker.xlsx',
  columns: [
    { header: 'Task ID', width: 10, type: 'text', align: 'center' },
    { header: 'Task', width: 32, type: 'text' },
    { header: 'Assignee', width: 16, type: 'text' },
    { header: 'Priority', width: 10, type: 'text', align: 'center' },
    { header: 'Status', width: 13, type: 'text', align: 'center' },
    { header: 'Due Date', width: 13, type: 'date', align: 'center' },
    { header: 'Days Left', width: 12, type: 'formula', align: 'center', formula: (r) => `=IFERROR(F${r}-TODAY(),"")` },
  ],
  summaryTitle: 'Task Summary',
  summary: [
    { label: 'Total Tasks', value: '=COUNTA(A2:A{n})' },
    { label: 'Completed', value: '=COUNTIF(E2:E{n},"Done")' },
    { label: 'In Progress', value: '=COUNTIF(E2:E{n},"In Progress")' },
    { label: 'Pending', value: '=COUNTIF(E2:E{n},"Pending")' },
    { label: 'High Priority', value: '=COUNTIF(D2:D{n},"High")' },
  ],
  instructions: [
    'HOW TO USE THIS TASK TRACKER',
    '',
    '1. Add each task starting from Row 2.',
    '2. Priority: High, Medium, Low.',
    '3. Status: Pending, In Progress, Done, Blocked.',
    '',
    'Generated by PDFplayOfficial AI Workspace',
    'https://pdfplayofficial.com',
  ],
  sampleData: [
    ['T-001', 'Fix login bug on production', 'Ahmed', 'High', 'In Progress', '2025-02-01'],
    ['T-002', 'Design new dashboard UI', 'Sara', 'Medium', 'Pending', '2025-02-10'],
    ['T-003', 'Update API documentation', 'Bilal', 'Low', 'Done', '2025-01-28'],
    ['T-004', 'Review pull request #142', 'Hassan', 'High', 'In Progress', '2025-02-02'],
    ['T-005', 'Set up CI/CD pipeline', 'Usman', 'Medium', 'Pending', '2025-02-15'],
    ['T-006', 'Write unit tests for auth', 'Ali', 'Medium', 'Pending', '2025-02-08'],
    ['T-007', 'Migrate database to Postgres', 'Fatima', 'High', 'Pending', '2025-02-20'],
    ['T-008', 'Customer feedback session', 'Ayesha', 'Medium', 'Done', '2025-01-25'],
    ['T-009', 'Optimize image loading', 'Mariam', 'Low', 'Pending', '2025-02-12'],
    ['T-010', 'Prepare Q1 report', 'Ahmed', 'High', 'In Progress', '2025-02-05'],
  ],
};

// ============================================================
// EXPORT ALL TEMPLATES
// ============================================================
export const templates: Template[] = [
  salesReport,
  invoice,
  expenseTracker,
  inventoryTracker,
  profitLoss,
  payrollSheet,
  customerList,
  monthlyBudget,
  habitTracker,
  todoList,
  studentMarks,
  attendanceSheet,
  gradeBook,
  projectTimeline,
  taskTracker,
];

// ============================================================
// TEMPLATE MATCHER
// ============================================================
export function findTemplate(prompt: string): Template | null {
  const lower = prompt.toLowerCase();

  let bestMatch: Template | null = null;
  let bestScore = 0;

  templates.forEach((template) => {
    let score = 0;
    template.keywords.forEach((keyword) => {
      if (lower.includes(keyword.toLowerCase())) {
        score += keyword.length;
      }
    });

    if (score > bestScore) {
      bestScore = score;
      bestMatch = template;
    }
  });

  return bestScore > 0 ? bestMatch : null;
}

// ============================================================
// ROW COUNT EXTRACTION
// ============================================================
export function extractRowCount(prompt: string, defaultValue = 20): number {
  const patterns = [
    /(\d+)\s*(rows?|bando|bandon|logo|items?|students?|employees?|entries)/i,
    /for\s+(\d+)/i,
    /(\d+)\s+(?:ke|ki|ka)/i,
  ];

  for (const pattern of patterns) {
    const match = prompt.match(pattern);
    if (match && match[1]) {
      const count = parseInt(match[1], 10);
      if (count > 0 && count <= 5000) {
        return count;
      }
    }
  }

  return defaultValue;
}